config/routes.rb
FunCoolVenture::Application.routes.draw do

  root to: "users#new"
  match 'homepage' => 'home#index', as: "homepage"  

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"
  get "sign_up" => "users#new", as: "sign_up"
  post "send_invitation" => "invitations#send_invite", as: "send_invitation"
  post "check_invitation" => "invitations#check_invite", as: "check_invitation"
  
  resources :rewards
  resources :sessions
  resources :users, only: [:new, :create]

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  attr_accessible :reward_id, :user_id

  belongs_to :reward
  belongs_to :user
  
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  attr_accessible :name, :user_id

  has_many :invitations
  has_many :users, through: :invitations
  
  def self.generate_random_id
    reward_ids= []
    rewards = Reward.all
    rewards.each do |reward|
      reward_ids.push(reward.id)
    end

    random_id = reward_ids.sample
    random_id
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :invitations
  has_many :rewards, through: :invitations

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def generate_device_id
    self.device_id = rand(1000000000)
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def self.check_user(invite_code)
    user = User.find_by_device_id(invite_code)
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  protected

  def authorize
    unless User.find_by_id(session[:user_id])
      redirect_to root_url, notice: "Login first"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :authorize
         
  def index
    @rewards = current_user.rewards
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  def send_invite
    if request.post?
      redirect_to homepage_path, notice: 'Invitation Sent'
    end
  end

  def check_invite
    if request.post?
      if params[:invitation_code].present?
        reward_id = Reward.generate_random_id
        user = User.check_user(params[:invitation_code])

        if current_user.rewards.count > 10
          redirect_to homepage_path, notice: "Reward exceed maximum!"
        elsif user.present?
          if user != current_user
            #Reward for person who invite
            sender = Invitation.new
            sender.user = user
            sender.reward_id = reward_id
            sender.save

            #Reward for person who get invited
            receiver = Invitation.new
            receiver.user = current_user
            receiver.reward_id = reward_id
            receiver.save

            #allow only for one time
            current_user.invited_by = user.id
            current_user.save

            redirect_to homepage_path, notice: "You got a new reward!"
          else
            redirect_to homepage_path, notice: "Cannot input self code"
          end
        else
          redirect_to homepage_path, notice: "Failure in proccess"
        end
      else
        render template: 'home/index'
      end
    end
  end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  
  before_filter :authorize
  
  def index
    @reward = Reward.all
  end

  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(params[:reward])
    @reward.user = current_user

    if @reward.save
      redirect_to root_url, notice: "Successfully created reward!"
    else
      render "new"
    end
  end

  def show

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to homepage_path, notice: "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.generate_device_id
    if @user.save
      redirect_to log_in_path, notice: "Signed up and login now!"
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<section id="forms">
  <div class="page-header">
    <h1>Forms</h1>
  </div>

  <div class="row">
    <div class="span10 offset1">
      <%= form_tag send_invitation_path, class: 'form-horizontal well'  do |f| %>
        <fieldset>
        <%= hidden_field_tag :send, params[:send] %>
        <% if current_user %>
          <legend>Your Invitation Code is <%= current_user.device_id %></legend>
            <%= submit_tag 'Send Invitation', class: "btn btn-primary" %>
        <% end %>
        </fieldset>
      <% end %>
    </div>

    <div class="span10 offset1">
      <%= form_tag check_invitation_path, class: 'form-horizontal well' do |f| %>
        <fieldset>
          <legend>
            Get your rewards by input invitation code</legend>
            <%= text_field_tag :invitation_code, params[:invitation_code], class: "input-x large", placeholder: 'Invitation Code' %>
            <% if current_user.invited_by.blank? %>
              <%= submit_tag 'Get Reward', class: "btn btn-primary" %>
            <% else %>
              <%= submit_tag 'Get Reward', class: "btn btn-primary", disabled: true %>
            <% end %>
        </fieldset>
      <% end %>
    </div>
  </div>

</section>

<section id="tables">
  <div class="page-header">
    <h1>Rewards</h1>
  </div>
  
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>No</th>
        <th>Reward</th>
      </tr>
    </thead>
    <tbody>
      <% if @rewards.present? %>
        <% count = 0 %>
        <% @rewards.each do |r| %>
        <tr>
          <td><%= count+=1 %></td>
          <td><%= r.name %></td>
        </tr>
        <% end %>
      <% else %>
        <tr>
          <td>No reward yet!</td>
        <tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FunCoolVenture</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

 <div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">

       <a class="brand" href="../">Fun and Cool Venture</a>
       <div class="nav-collapse collapse" id="main-menu">
        <ul class="nav" id="main-menu-left">
          <% if current_user %>
          <li><%= link_to  "Log out from #{current_user.email}", log_out_path, html: { id: 'swatch-link'} %></li>
          <% else %>
          <li><%= link_to "Sign up", sign_up_path, html: { id: 'swatch-link'} %></li>
          <li><%= link_to "log in", log_in_path, html: { id: 'swatch-link'} %></li>
          <% end %>
        </ul>

        <ul class="nav pull-right" id="main-menu-right">
          <% flash.each do |name, msg| %>
            <div class="alert alert-info">
            <a class="close">&times;</a>
            <strong><%= content_tag :div, msg, :id => "flash_#{name}" %></strong>
            </div>
          <% end %>
        </ul>


       </div>
     </div>
   </div>
 </div>


<div class="container">


  <%= yield %>
</div>



</body>
</html>

app/views/rewards/new.html.erb
<section id="forms">
  <h1>Create Reward</h1>

  <%= form_for @reward do |f| %>
    <% if @reward.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @reward.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </p>
    <p class="btn"><%= f.submit %></p>
  <% end %>
</section>

app/views/users/new.html.erb
<section id="forms">
  <div class="page-header">
  </div>

  <div class="row">
    <div class="span10 offset1">
      <%= form_for @user, html: { class: 'form-horizontal well' } do |f| %>
        <% if @user.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <fieldset>
          <legend>
            Sign Up Information</legend>
            <div class="control-group">
            <%= f.text_field :email, class: "input-x large", placeholder: 'Email' %><br/>
            </div>

            <div class="control-group">
            <%= f.password_field :password, class: "input-x large", placeholder: 'Password' %><br/>
            </div>

            <div class="control-group">
            <%= f.password_field :password_confirmation, class: "input-x large", placeholder: 'Password_confirmation' %><br/>
            </div>

            <%= f.submit 'Join', class: "btn btn-primary" %>
        </fieldset>
      <% end %>
    </div>
  </div>
</section>